add readme and doc
valitydev/scrooge pull request #2
Opened 2022-02-07 14:45 UTC by ggmaleva

2022-02-07 15:22 UTC, mr-impossibru requested changes
Не хватает описания взаимодействия со счетами:
- CRUD для сущностей
- причина связывания Account с другими сущностями (id счета у провайдера не всегда может быть равен номеру банковского счета)

2022-02-07 15:22 UTC, mr-impossibru commented on README.md
> +- хранение и обновление баланса выплатных аккаунтов путем опроса адаптеров
имхо вместо `аккаунт` лучше использовать `счет`

2022-02-08 08:54 UTC, strug reviewed
![image](https://user-images.githubusercontent.com/3994765/152951846-1b3f07b5-4c6e-4937-9d67-f18586f2a98c.png)
вот тут бы сразу в WIthdrawallService запроси состояние, вроде логично звучит и его передал вместо id

2022-02-10 14:37 UTC, ggmaleva commented
> Не хватает описания взаимодействия со счетами:
> 
> * CRUD для сущностей
> * причина связывания Account с другими сущностями (id счета у провайдера не всегда может быть равен номеру банковского счета)

Скорее всего будет чуть другая схема данных после того как команда эрланга сделают новую ручку. Если будет необходимость добавлю описание CRUD для сущностей

2022-02-10 14:39 UTC, ggmaleva commented
> Я бы добавил словестный алгоритм работы с примером. После этого вкатиться в то что происходит в адаптере и на схемах будет сильно проще ИМХО.

Добавил чуть подробное словесное описание алгоритма

2022-02-11 12:43 UTC, mr-impossibru reviewed
Пара моментов:
- не описан случай, если мы идем на ручку банка. Будет ли для этого отдельный сервис или сам scrooge будет ходить?
- На схеме с доминантой какой-то пустой левый сервис или у меня криво отображается
<img width="344" alt="image" src="https://user-images.githubusercontent.com/64555470/153593337-95356210-94fa-412b-a525-ff5f0ac64516.png">

2022-02-11 13:03 UTC, ggmaleva commented
> Пара моментов:
> 
> * не описан случай, если мы идем на ручку банка. Будет ли для этого отдельный сервис или сам scrooge будет ходить?
> * На схеме с доминантой какой-то пустой левый сервис или у меня криво отображается
> 
> <img alt="image" width="344" src="https://user-images.githubusercontent.com/64555470/153593337-95356210-94fa-412b-a525-ff5f0ac64516.png">

1) Я это объединил одной абстракцией Adapter (внешний сервис). Думаю, что для банков будут аналогичные адаптеры с тем же протоколом, что и для выплатных адаптеров. И для scrooge будет без разницы банк это или адапетр. 
2) На самом деле я забыл дропнуть схему доминанты. Переиграли алгоритм. 
Должна будет появится новая ручка от эрланга , по которой будем получать информацию по опциям адаптера, его url и еще что-то. Это все будет происходить в синхроне при получении нового события (пояснил это в описании работы сервиса). И в доминанте необходимость пропадает. Отвечая на твой вопрос -  если выбрать белую схему гитхаба, то там все норм отображается. Это легенда схемы, там написано, что это внешний сервис :)

2022-02-11 13:08 UTC, mr-impossibru submitted a review, later dismissed
> И в доминанте необходимость пропадает 

звучит прекрасно

2022-02-15 16:27 UTC, mr-impossibru reviewed
Вопрос касательно зависимости от `party-management`, у нас есть сервис `vortigon` и, если мне не изменяет память, он должен заменить `party-management`.
Если это действительно так, то надо узнать когда `vortigon` выведут в прод и предварительно внести изменения для взаимодействия со `scrooge`.

2022-02-18 14:48 UTC, ggmaleva commented
> Вопрос касательно зависимости от `party-management`, у нас есть сервис `vortigon` и, если мне не изменяет память, он должен заменить `party-management`. Если это действительно так, то надо узнать когда `vortigon` выведут в прод и предварительно внести изменения для взаимодействия со `scrooge`.

Уточнил, это независимые сервисы и они про разную функциональность.
Так что будем использовать party-management

2022-02-18 15:29 UTC, mr-impossibru approved these changes

2022-02-21 08:53 UTC, D-Baykov approved these changes

2022-02-21 11:47 UTC, merged